---
title: "Comparison of Preprocessing Methods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
devtools::install_github("dr-JT/pupillometry", ref = "testing")
```

```{r}
library(pupillometry)
library(ggplot2)
```

```{r message = FALSE, warning = FALSE}
## Preprocessing Parameters ####
import <- "../Raw"
pattern <- "*.txt"
output <- "../Preprocessed"
task <- "Pitch_Discrimination"
eyetracker <- "smi"

# Eyetrackers save the subject # information in different ways and is not always easy to obtain
# The most versatile method is to extract it from the datafile name. You need to identify a 
# unique subj.prefix pattern and subj.suffix pattern that surrounds the subject # in the 
# datafile name. In this case it would be 
subj.prefix <- "n_" # There are multiple underscores in this datafile name so it needs to be more specific "n_"
subj.suffix <- "-"

subset <- "default"
trial.exclude <- c()

eye.recorded <- "both"
eye.use <- "left"
hz <- 250
startrecording.message <- "default"
startrecording.match <- "exact"
trialonset.message <- "Tone 1" 

# Intertrial interval (Fixation) was 2000 ms but 
# I am choosing to set only the last 1000 ms as pre-trial
pretrial.duration <- 1000

velocity <- ""
margin <- ""
missing.allowed <- .75
interpolate <- TRUE
interpolate.maxgap <- 750
smooth <- TRUE
smooth.window <- 500
bc = FALSE
downsample.binlength <- NULL
################################
```

```{r}
interpolate.type <- "linear"
smooth.type <- "mwa"
method.first <- "smooth"
preprocess(import = import, pattern = pattern, output = output, taskname = task, eyetracker = eyetracker,
           subj.prefix = subj.prefix, subj.suffix = subj.suffix,
           subset = subset, trial.exclude = trial.exclude,
           eye.recorded = eye.recorded, eye.use = eye.use, hz = hz,
           startrecording.message = startrecording.message, startrecording.match = startrecording.match,
           trialonset.message = trialonset.message, pretrial.duration = pretrial.duration,
           velocity = velocity, margin = margin, missing.allowed = missing.allowed,
           interpolate = interpolate, interpolate.type = interpolate.type, interpolate.maxgap = interpolate.maxgap,
           smooth = smooth, smooth.type = smooth.type, smooth.window = smooth.window, method.first = method.first,
           bc = bc, baselineoffset.message = baselineoffset.message, bc.duration = bc.duration, bc.type = bc.type,
           downsample.binlength = downsample.binlength)
```

```{r}
method.first <- "interpolate"
preprocess(import = import, pattern = pattern, output = output, taskname = task, eyetracker = eyetracker,
           subj.prefix = subj.prefix, subj.suffix = subj.suffix,
           subset = subset, trial.exclude = trial.exclude,
           eye.recorded = eye.recorded, eye.use = eye.use, hz = hz,
           startrecording.message = startrecording.message, startrecording.match = startrecording.match,
           trialonset.message = trialonset.message, pretrial.duration = pretrial.duration,
           velocity = velocity, margin = margin, missing.allowed = missing.allowed,
           interpolate = interpolate, interpolate.type = interpolate.type, interpolate.maxgap = interpolate.maxgap,
           smooth = smooth, smooth.type = smooth.type, smooth.window = smooth.window, method.first = method.first,
           bc = bc, baselineoffset.message = baselineoffset.message, bc.duration = bc.duration, bc.type = bc.type,
           downsample.binlength = downsample.binlength)
```

## Trial 1
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 1,
                title = paste("Trial", 1, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial1-", "smooth.type.png", sep = ""))
```

## Trial 2
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 2,
                title = paste("Trial", 2, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial2-", "smooth.type.png", sep = ""))
```

## Trial 3
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 3,
                title = paste("Trial", 3, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial3-", "smooth.type.png", sep = ""))
```

## Trial 4
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 4,
                title = paste("Trial", 4, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial4-", "smooth.type.png", sep = ""))
```

## Trial 5
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 5,
                title = paste("Trial", 5, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial5-", "smooth.type.png", sep = ""))
```

## Trial 6
```{r}
plot.comparison(import = output, 
                files = c("Pitch_Discrimination_19_PupilData_smoothed_hann.txt",
                          "Pitch_Discrimination_19_PupilData_smoothed_mwa.txt",
                          "Pitch_Discrimination_19_PupilData_naremoved.txt"),
                labels = c("hann",
                           "mwa",
                           "No Preprocessing"), 
                trial = 6,
                title = paste("Trial", 6, sep = " "),
                legend.title = "smooth.type") 
ggsave(paste("Trial6-", "smooth.type.png", sep = ""))
```

